apiVersion: batch/v1
kind: Job
metadata:
  name: annotate-service-account
  annotations:
    "helm.sh/hook": post-install
spec:
  template:
    spec:
      serviceAccountName: <service-account-with-patch-permission>
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - >
              kubectl patch serviceaccount <service-account-name> -n {{ .Release.Namespace }} 
              -p '{"metadata": {"annotations": {"your.annotation/key": "your-value"}}}'
      restartPolicy: Never